# Generated by Django 3.0.5 on 2021-03-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210319_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
