# Generated by Django 3.0.5 on 2021-03-15 15:33

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210315_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option',
            field=jsonfield.fields.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
