# Generated by Django 3.0.5 on 2021-03-15 15:57

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210315_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizassign',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizassign',
            name='response',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
