# Generated by Django 3.0.5 on 2021-03-22 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignquiz',
            name='user',
        ),
        migrations.AddField(
            model_name='assignquiz',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
