# Generated by Django 3.0.5 on 2021-03-23 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20210322_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learn_new', models.PositiveIntegerField()),
                ('like_participating', models.PositiveIntegerField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('participate_again', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5)),
                ('time_sufficient', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5)),
                ('attend_webinar', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5)),
                ('language_english', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5)),
                ('mini_course', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=5)),
                ('next_contest', models.CharField(choices=[('Puzzle Solving', 'Puzzle Solving'), ('Problem solving strategies', 'Problem solving strategies'), ('Mental Maths', 'Mental Maths'), ('Mathematics to entertain your spirit', 'Mathematics to entertain your spirit')], max_length=150)),
                ('suggestions', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
