# Generated by Django 3.0.5 on 2021-03-23 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210323_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='quiz_id',
            field=models.ForeignKey(default='4f3b3f6b-e1d0-4ca9-986b-1ec66aae968f', on_delete=django.db.models.deletion.CASCADE, to='api.Quiz'),
        ),
    ]
