# Generated by Django 3.0.5 on 2021-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210325_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignquiz',
            name='quiz_starttime',
            field=models.DateTimeField(blank=True, default='2021-03-24 18:00:00', null=True),
        ),
    ]
