# Generated by Django 3.0.5 on 2021-03-26 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userquizsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizsession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
