# Generated by Django 3.0.5 on 2021-03-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_assignquiz_quiz_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignquiz',
            name='quiz_starttime',
        ),
    ]
