# Generated by Django 3.0.5 on 2021-03-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userquizsession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizsession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
