# Generated by Django 3.0.5 on 2021-03-26 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210326_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquizsession',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
