# Generated by Django 3.0.5 on 2021-03-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210326_1121'),
        ('api', '0010_remove_assignquiz_quiz_starttime'),
    ]

    operations = [
    ]
