# Generated by Django 3.0.5 on 2021-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20210327_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dificulty_tag',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='subject_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='topic_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
