# Generated by Django 3.0.5 on 2021-03-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210327_0913'),
        ('api', '0013_merge_20210328_1133'),
    ]

    operations = [
    ]
