# Generated by Django 3.0.5 on 2021-03-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFromFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userdata', models.FileField(max_length=1000, upload_to='userdata')),
            ],
        ),
    ]
