# Generated by Django 3.0.5 on 2021-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userfromfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfromfile',
            name='filename',
            field=models.CharField(blank=True, default='output.csv', max_length=100),
        ),
    ]
