name: Django CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Digitalocean droplet
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password:  ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/quiz_backend 
            git stash
            git fetch
            git pull 
            pip3 install -r requirements.txt
            systemctl stop quizbk.service
            systemctl restart nginx
